name: Maven Build
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
  workflow_call:
    inputs:
      repository_name:
        required: true
        type: string
      branch_name:
        required: false
        type: string
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        if: ${{ true && github.repository != 'numanturkeri/shared-pipeline-templates' }}
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository_name }}
          ref: ${{ inputs.branch_name }}

      - name: Cache npm dependencies
        if: ${{ true && github.repository != 'numanturkeri/shared-pipeline-templates' }}
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install Node.js
        if: ${{ true && github.repository != 'numanturkeri/shared-pipeline-templates' }}
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install project dependencies
        if: ${{ true && github.repository != 'numanturkeri/shared-pipeline-templates' }}
        run: | 
          cd frontend
          npm i -f

      - name: Build with npm
        if: ${{ true && github.repository != 'numanturkeri/shared-pipeline-templates' }}
        run: |
          cd frontend
          npm run build