name: Bump version

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
  workflow_call:
    inputs:
      repository_name:
        required: true
        type: string
      dry_run:
        required: true
        type: boolean
      prefix:
        required: false
        type: string
        default: v
    outputs:
      newTag:
        description: "The newest tag of the repository"
        value: ${{ jobs.tagging.outputs.newTag }}

jobs:
  tagging:
    runs-on: ubuntu-latest
    outputs:
      newTag: ${{ steps.taggerDryRun.outputs.new_tag }}
    steps:
      - name: Checkout repository
        if: ${{ github.repository != 'numanturkeri/shared-pipeline-templates' }}
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository_name }}
          ref: main

      #Dry run to estimate the next tag version
      - name: Bump version and push tag
        if: ${{ true && github.repository != 'numanturkeri/shared-pipeline-templates' }}
        id: taggerDryRun
        uses: miguelfito/github-bump-and-tag-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ${{ inputs.prefix }}
          dry_run: ${{ inputs.dry_run }}

      - name: Generate output
        id: step1
        run: |
          echo ${{ steps.taggerDryRun.outputs.new_tag }} > output.txt

      - name: Archive output
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: output.txt
