name: Deploy

on:
  push:
    branches:
      - main
  workflow_call:
    inputs:
      repository_name:
        required: true
        type: string
      registry_username:
        required: true
        type: string
    secrets:
      registry_password:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      EKS_REGION:
        required: true
      EKS_CLUSTER_NAME:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository_name }}
          ref: main

      - name: Download output
        uses: actions/download-artifact@v4
        with:
          name: output-${{ github.run_id }}-${{ github.run_number }}-${{ github.sha }}

      - name: Read output
        id: step2
        run: |
          cat tag_version.txt
          echo "NEW_TAG=$(cat tag_version.txt)" >> $GITHUB_ENV

      - name: Install AWS CLI
        run: |
          set -x  # Adımları ayrıntılı olarak görmek için
          sudo apt-get update
          sudo apt-get install -y unzip
          curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update --bin-dir /usr/local/bin

      - name: Configure AWS CLI
        run: |
          set -x  # Adımları ayrıntılı olarak görmek için
          aws configure set region ${{ secrets.EKS_REGION }}
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Install Kubernetes CLI
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Configure kubectl for EKS cluster
        run: |
          aws eks --region ${{ secrets.EKS_REGION }} update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ inputs.registry_username }}
          password: ${{ secrets.registry_password }}

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Install Helm Diff Plugin
        run: |
          helm plugin install https://github.com/databus23/helm-diff

      - name: Install Helmfile
        run: |
          curl -L https://github.com/roboll/helmfile/releases/latest/download/helmfile_linux_amd64 -o helmfile
          chmod +x helmfile
          sudo mv helmfile /usr/local/bin/

      - name: Deploy Diff
        env:
          CONTAINER_REGISTRY_USERNAME: ${{ inputs.registry_username }}
          CONTAINER_REGISTRY_PASSWORD: ${{ secrets.registry_password }}
        run: |
          cd deploy
          helmfile diff    

      - name: Deploy Apply
        env:
          CONTAINER_REGISTRY_USERNAME: ${{ inputs.registry_username }}
          CONTAINER_REGISTRY_PASSWORD: ${{ secrets.registry_password }}
        run: |
          cd deploy
          helmfile apply